apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment
  labels:
    app: tomcat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: aaarpitaaa/apacheimage1:latest
        ports:
        - containerPort: 9090
        readinessProbe:
          httpGet:
            path: /onlinebookstore/index.html
            port: 9090
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /onlinebookstore/index.html
            port: 9090
          initialDelaySeconds: 15
          periodSeconds: 10
# init-container
      initContainers:
      - name: init-eks-service
        image: aaarpitaaa/apacheimage1:latest
        command: ['sh', '-c', "touch /usr/local/tomcat/hello.txt"]
#      - name: sidecar-eks-service
#        image: aaarpitaaa/apacheimage1:latest
#        command: ["sh","-c","while true; "touch /usr/local/tomcat/hello.txt"; sleep 30; done"]
#        volumeMounts:
#          - name: shared-logs
#            mountPath: /var/log/
#      volumes:
#      - name: shared-logs
#        emptyDir: {}
